---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config/external/zones
    default_ttl: 3600
    enforce_order: True
  target:
    class: octodns_bind.Rfc2136Provider
    host: env/TARGET_HOST
    port: 53
    ipv6: False
    timeout: 15
    key_name: env/AXFR_KEY_NAME
    key_secret: env/AXFR_KEY_SECRET
    key_algorithm: hmac-sha512
  
zones:
  home.molier.net.:
    sources:
      - config
    targets:
      - target